require("config.coderunner")
require("config.competitest")
-- require("config.git-graph")
require("config.gitsigns")
require("config.lualine")
require("config.nvim-tree")
require("config.telescope")
require("config.cmp")
require("config.lsp")
require("config.treesitter")
require("config.which-key")
